const { chromium } = require('playwright');
const path = require('path');
(async () => {
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', err => errors.push(err.message + '\n' + err.stack));
  page.on('console', msg => { if (msg.type() === 'error' && !msg.text().includes('TUNNEL')) errors.push('console: ' + msg.text()); });
  await page.goto('file://' + path.join(__dirname, 'test.html'));
  await page.evaluate(() => { const g = document.getElementById('auth-gate'); if (g) g.hidden = true; });
  await page.waitForTimeout(300);
  await page.click('[data-tab="menu"]');
  await page.waitForTimeout(150);
  const menuText = await page.evaluate(() => document.getElementById('view-root').textContent);
  console.log('menu incluye "Importar desde tu correo":', menuText.includes('Importar desde tu correo'));
  await page.click('[data-menu-open="importarcorreo"]');
  await page.waitForTimeout(200);
  await page.screenshot({ path: 'shot43_00_loading_or_error.png', fullPage: true });
  const screenText = await page.evaluate(() => document.getElementById('view-root').textContent.replace(/\s+/g,' ').trim());
  console.log('pantalla tras abrir (sin red a Supabase en este sandbox, se espera un error prolijo):', screenText);
  console.log('ERRORS:', JSON.stringify(errors));
  await browser.close();
})();
